# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from slurm_workflows import ds_service_pb2 as slurm__workflows_dot_ds__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in slurm_workflows/ds_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DsServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MapSet = channel.unary_unary(
                '/DsService/MapSet',
                request_serializer=slurm__workflows_dot_ds__service__pb2.MapSetRequest.SerializeToString,
                response_deserializer=slurm__workflows_dot_ds__service__pb2.Empty.FromString,
                _registered_method=True)
        self.MapGet = channel.unary_unary(
                '/DsService/MapGet',
                request_serializer=slurm__workflows_dot_ds__service__pb2.MapGetRequest.SerializeToString,
                response_deserializer=slurm__workflows_dot_ds__service__pb2.MapGetResponse.FromString,
                _registered_method=True)
        self.TaskAdd = channel.unary_unary(
                '/DsService/TaskAdd',
                request_serializer=slurm__workflows_dot_ds__service__pb2.TaskAddRequest.SerializeToString,
                response_deserializer=slurm__workflows_dot_ds__service__pb2.Empty.FromString,
                _registered_method=True)
        self.TaskStatus = channel.unary_unary(
                '/DsService/TaskStatus',
                request_serializer=slurm__workflows_dot_ds__service__pb2.TaskStatusRequest.SerializeToString,
                response_deserializer=slurm__workflows_dot_ds__service__pb2.TaskStatusResponse.FromString,
                _registered_method=True)
        self.TaskGet = channel.unary_unary(
                '/DsService/TaskGet',
                request_serializer=slurm__workflows_dot_ds__service__pb2.TaskGetRequest.SerializeToString,
                response_deserializer=slurm__workflows_dot_ds__service__pb2.TaskGetResponse.FromString,
                _registered_method=True)
        self.TaskDone = channel.unary_unary(
                '/DsService/TaskDone',
                request_serializer=slurm__workflows_dot_ds__service__pb2.TaskDoneRequest.SerializeToString,
                response_deserializer=slurm__workflows_dot_ds__service__pb2.Empty.FromString,
                _registered_method=True)
        self.Requeue = channel.unary_unary(
                '/DsService/Requeue',
                request_serializer=slurm__workflows_dot_ds__service__pb2.RequeueRequest.SerializeToString,
                response_deserializer=slurm__workflows_dot_ds__service__pb2.Empty.FromString,
                _registered_method=True)


class DsServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def MapSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MapGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskAdd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskDone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Requeue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MapSet': grpc.unary_unary_rpc_method_handler(
                    servicer.MapSet,
                    request_deserializer=slurm__workflows_dot_ds__service__pb2.MapSetRequest.FromString,
                    response_serializer=slurm__workflows_dot_ds__service__pb2.Empty.SerializeToString,
            ),
            'MapGet': grpc.unary_unary_rpc_method_handler(
                    servicer.MapGet,
                    request_deserializer=slurm__workflows_dot_ds__service__pb2.MapGetRequest.FromString,
                    response_serializer=slurm__workflows_dot_ds__service__pb2.MapGetResponse.SerializeToString,
            ),
            'TaskAdd': grpc.unary_unary_rpc_method_handler(
                    servicer.TaskAdd,
                    request_deserializer=slurm__workflows_dot_ds__service__pb2.TaskAddRequest.FromString,
                    response_serializer=slurm__workflows_dot_ds__service__pb2.Empty.SerializeToString,
            ),
            'TaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.TaskStatus,
                    request_deserializer=slurm__workflows_dot_ds__service__pb2.TaskStatusRequest.FromString,
                    response_serializer=slurm__workflows_dot_ds__service__pb2.TaskStatusResponse.SerializeToString,
            ),
            'TaskGet': grpc.unary_unary_rpc_method_handler(
                    servicer.TaskGet,
                    request_deserializer=slurm__workflows_dot_ds__service__pb2.TaskGetRequest.FromString,
                    response_serializer=slurm__workflows_dot_ds__service__pb2.TaskGetResponse.SerializeToString,
            ),
            'TaskDone': grpc.unary_unary_rpc_method_handler(
                    servicer.TaskDone,
                    request_deserializer=slurm__workflows_dot_ds__service__pb2.TaskDoneRequest.FromString,
                    response_serializer=slurm__workflows_dot_ds__service__pb2.Empty.SerializeToString,
            ),
            'Requeue': grpc.unary_unary_rpc_method_handler(
                    servicer.Requeue,
                    request_deserializer=slurm__workflows_dot_ds__service__pb2.RequeueRequest.FromString,
                    response_serializer=slurm__workflows_dot_ds__service__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DsService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MapSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DsService/MapSet',
            slurm__workflows_dot_ds__service__pb2.MapSetRequest.SerializeToString,
            slurm__workflows_dot_ds__service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MapGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DsService/MapGet',
            slurm__workflows_dot_ds__service__pb2.MapGetRequest.SerializeToString,
            slurm__workflows_dot_ds__service__pb2.MapGetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TaskAdd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DsService/TaskAdd',
            slurm__workflows_dot_ds__service__pb2.TaskAddRequest.SerializeToString,
            slurm__workflows_dot_ds__service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DsService/TaskStatus',
            slurm__workflows_dot_ds__service__pb2.TaskStatusRequest.SerializeToString,
            slurm__workflows_dot_ds__service__pb2.TaskStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TaskGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DsService/TaskGet',
            slurm__workflows_dot_ds__service__pb2.TaskGetRequest.SerializeToString,
            slurm__workflows_dot_ds__service__pb2.TaskGetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TaskDone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DsService/TaskDone',
            slurm__workflows_dot_ds__service__pb2.TaskDoneRequest.SerializeToString,
            slurm__workflows_dot_ds__service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Requeue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DsService/Requeue',
            slurm__workflows_dot_ds__service__pb2.RequeueRequest.SerializeToString,
            slurm__workflows_dot_ds__service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
