# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: slurm_workflows/ds-service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'slurm_workflows/ds-service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n slurm_workflows/ds-service.proto\"\x07\n\x05\x45mpty\"+\n\rMapSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"\x1c\n\rMapGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1f\n\x0eMapGetResponse\x12\r\n\x05value\x18\x01 \x01(\x0c\"c\n\x0eTaskAddRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\r\n\x05queue\x18\x02 \x03(\t\x12\x10\n\x08priority\x18\x03 \x01(\x01\x12\x10\n\x08\x66unction\x18\x04 \x01(\x0c\x12\r\n\x05input\x18\x05 \x01(\x0c\"$\n\x11TaskStatusRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"?\n\x12TaskStatusResponse\x12\x19\n\x05state\x18\x01 \x01(\x0e\x32\n.TaskState\x12\x0e\n\x06output\x18\x02 \x01(\x0c\"2\n\x0eTaskGetRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\r\n\x05queue\x18\x02 \x03(\t\"C\n\x0fTaskGetResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x10\n\x08\x66unction\x18\x02 \x01(\x0c\x12\r\n\x05input\x18\x03 \x01(\x0c\"2\n\x0fTaskDoneRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06output\x18\x02 \x01(\x0c\"#\n\x0eRequeueRequest\x12\x11\n\ttimeout_s\x18\x01 \x01(\x01*1\n\tTaskState\x12\t\n\x05Ready\x10\x00\x12\x0b\n\x07Running\x10\x01\x12\x0c\n\x08\x43omplete\x10\x02\x32\xb9\x02\n\tDsService\x12\"\n\x06MapSet\x12\x0e.MapSetRequest\x1a\x06.Empty\"\x00\x12+\n\x06MapGet\x12\x0e.MapGetRequest\x1a\x0f.MapGetResponse\"\x00\x12$\n\x07TaskAdd\x12\x0f.TaskAddRequest\x1a\x06.Empty\"\x00\x12\x37\n\nTaskStatus\x12\x12.TaskStatusRequest\x1a\x13.TaskStatusResponse\"\x00\x12.\n\x07TaskGet\x12\x0f.TaskGetRequest\x1a\x10.TaskGetResponse\"\x00\x12&\n\x08TaskDone\x12\x10.TaskDoneRequest\x1a\x06.Empty\"\x00\x12$\n\x07Requeue\x12\x0f.RequeueRequest\x1a\x06.Empty\"\x00\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'slurm_workflows.ds_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKSTATE']._serialized_start=567
  _globals['_TASKSTATE']._serialized_end=616
  _globals['_EMPTY']._serialized_start=36
  _globals['_EMPTY']._serialized_end=43
  _globals['_MAPSETREQUEST']._serialized_start=45
  _globals['_MAPSETREQUEST']._serialized_end=88
  _globals['_MAPGETREQUEST']._serialized_start=90
  _globals['_MAPGETREQUEST']._serialized_end=118
  _globals['_MAPGETRESPONSE']._serialized_start=120
  _globals['_MAPGETRESPONSE']._serialized_end=151
  _globals['_TASKADDREQUEST']._serialized_start=153
  _globals['_TASKADDREQUEST']._serialized_end=252
  _globals['_TASKSTATUSREQUEST']._serialized_start=254
  _globals['_TASKSTATUSREQUEST']._serialized_end=290
  _globals['_TASKSTATUSRESPONSE']._serialized_start=292
  _globals['_TASKSTATUSRESPONSE']._serialized_end=355
  _globals['_TASKGETREQUEST']._serialized_start=357
  _globals['_TASKGETREQUEST']._serialized_end=407
  _globals['_TASKGETRESPONSE']._serialized_start=409
  _globals['_TASKGETRESPONSE']._serialized_end=476
  _globals['_TASKDONEREQUEST']._serialized_start=478
  _globals['_TASKDONEREQUEST']._serialized_end=528
  _globals['_REQUEUEREQUEST']._serialized_start=530
  _globals['_REQUEUEREQUEST']._serialized_end=565
  _globals['_DSSERVICE']._serialized_start=619
  _globals['_DSSERVICE']._serialized_end=932
# @@protoc_insertion_point(module_scope)
